### ISSUE TITLE
[Patient Intake Sample] Implement Patient Intake Processor Bot

### ISSUE THREAD

**Issue by pamella** [medplum/medplum#4799] opened 2024-07-04 18:26 UTC
- Implement a bot to process the QuestionnaireResponse, update the Patient resource, and create additional resources as needed. 
- Write tests and remove the `--passWithNoTests` flag from the test scripts (package.json).

**Comment by rahul1** [comment] 2024-07-05 05:04
I think this is a duplicate of #4802 . I'm closing this in favor of the other

**Closed by rahul1** 2024-07-05 05:04 UTC
