### ISSUE TITLE
No Resource input for filter with choice of type input

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#2616] opened 2023-08-03 20:43 UTC
## Repro
- Navigate to https://app.medplum.com/Encounter
- Click "Filters"
- Set "Field" to "Subject"
- Set "operation" to "equals"
- Set "Value" to "Patient"

Previously, a final input would appear that would allow you to search by Patient name / uuid. This input no longer appears

<img width="890" alt="image" src="https://github.com/medplum/medplum/assets/1259236/47a2750b-3610-4287-bab8-f651cf11900d">

**Comment by codyebberson** [comment] 2023-08-04 00:33
Good bug.

This was caused by a recent change.
- Change: https://github.com/medplum/medplum/commit/8fcd088e171a6728fbb556d93b6b37685f6fab36
- Specific line: https://github.com/medplum/medplum/blob/main/packages/react/src/ResourceInput/ResourceInput.tsx#L119

Arguably the real bug is here, where `<SearchFilterValueInput>` sets a bogus `Reference` for the `defaultValue`:

https://github.com/medplum/medplum/blob/main/packages/react/src/SearchFilterValueInput/SearchFilterValueInput.tsx#L26

My guess is we could fix it by changing this line:

```tsx
defaultValue={{ reference: props.defaultValue }}
```

To this:

```tsx
defaultValue={props.defaultValue ? { reference: props.defaultValue } : undefined}
```

OR, we update `<ResourceInput>` to be more resilient to bad `Reference` inputs.

Or both.

**Comment by codyebberson** [comment] 2023-08-04 18:28
Fixed in https://github.com/medplum/medplum/pull/2625

**Closed by codyebberson** 2023-08-04 18:28 UTC
Labels: bug, good first issue, medplum-app
