### ISSUE TITLE
Use aws-sdk-client-mock

### ISSUE THREAD

**Issue by codyebberson** [medplum/medplum#1423] opened 2023-01-20 14:13 UTC
https://github.com/m-radzikowski/aws-sdk-client-mock

Looks much better than our manual mocks.

h/t @elliot-nelson

**Comment by atifnimran** [comment] 2023-02-03 06:27
Yes

**Comment by taylorqj** [comment] 2023-02-21 05:27
Have you taken a look at [LocalStack](https://github.com/localstack/localstack)? I've used this in the past as a replacement to mocking external cloud services.

**Comment by Paul-Taiwo** [comment] 2023-06-26 13:15
Hi @codyebberson. I would love to give this a try

**Comment by mattwiller** [comment] 2023-06-26 17:28
@Paul-Taiwo Please go right ahead!

**Comment by brandonin** [comment] 2023-06-30 04:28
Howdy @mattwiller :)

**Comment by mattwiller** [comment] 2023-06-30 17:00
Oh hey @brandonin! 👋

**Comment by Paul-Taiwo** [comment] 2023-07-06 10:44
Hey @mattwiller, I see @brandonin has a PR for the remaining manual mocks. Should I go ahead to work on it?

**Comment by Paul-Taiwo** [comment] 2023-07-19 22:48
Hi @codyebberson, I've completed all the tasks and updated the mocks. However, I noticed that the issue is still marked as open. Could you please review the changes and let me know if there's anything else I can do to help move this forward? Thank you!

**Comment by mattwiller** [comment] 2023-07-19 23:18
I went ahead and closed it — thanks so much @Paul-Taiwo and @brandonin 🎉🎉

**Closed** 2023-07-19 23:17 UTC
Labels: good first issue
