### ISSUE TITLE
Support linking to resources in targeted project on app.medplum.com from external system

### ISSUE THREAD

**Issue by dillonstreator** [medplum/medplum#4562] opened 2024-05-15 14:24 UTC
Linking to a resource in app.medplum.com from an external application results in 404 if the currently authed project in Medplum does not match the external application environment. There is cognitive overhead and friction in identifying and switching to the proper project manually.

It would be valuable for external applications to inject the Project.id into a query parameter that app.medplum.com respects. If the currently authed project matches the target project id, proceed as normal. If it does not match, attempt to automatically switch projects. If unauthed in the target project, I'd expect to be redirected to the intended resource after authentication.

**Comment by rahul1** [comment] 2024-05-16 13:26
Hi @dillonstreator , this is a duplicate of [this ticket here](https://github.com/medplum/medplum/issues/3987). I'm closing this one to remove the due, but take a look at the discussoin there

**Closed by rahul1** 2024-05-16 13:26 UTC
