### ISSUE TITLE
Self hosted system login and register not working

### ISSUE THREAD

**Issue by nikul-tc** [medplum/medplum#1489] opened 2023-02-08 12:52 UTC
Hello Medplum,

I have setup self hosted Medplum on GCP VM using ubuntu instance.
APIs are working properly and healthcheck API is also working perfectly.
I bring to login with default username and password, when I try to login or register nothing happens, No errors on console, not on network tab.

I am trying to figure issue from last two days but nothing works.
Can you please help me with this issue.

I appreciate your quick response.

Thanks

**Comment by codyebberson** [comment] 2023-02-08 17:19
Hi @nikul-tc 

The most likely issue is sending automated emails.  The Medplum server project currently assumes that AWS SES is available.  There are probably some unhandled 500 errors in your server logs.

Assuming that the problem is emails:

My understanding is that GCP does not have an AWS SES equivalent (source: https://cloud.google.com/compute/docs/tutorials/sending-mail).  

In the medium term (2-3 months), this could be remedied with the proposed [plugin architecture](https://github.com/medplum/medplum/discussions/1424)

In the short term:

* You could setup an AWS account on the Ubuntu host using `.aws/credentials` that can use AWS SES
* We could quickly add an option to disable automated emails, and you could send emails using your provider of choice using Medplum Bots
* We could add an option to send via SMTP.  That would require some development resources, so we would need to do a planning exercise.

**Comment by nikul-tc** [comment] 2023-02-09 05:20
@codyebberson,

I moved on AWS CDK and its working now.

Thanks

**Comment by reshmakh** [comment] 2023-02-09 23:16
@nikul-tc - going to close this for the time being given the CDK is working.  Feel free to message in Discord with follow ups

**Closed by reshmakh** 2023-02-09 23:16 UTC
Labels: self-host
